# Generated by Django 5.2.6 on 2025-09-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('method', models.CharField(choices=[('telegram', 'Telegram Payments'), ('card', 'Банковская карта'), ('cash', 'Наличные'), ('online', 'Онлайн-платеж')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Неудачно'), ('cancelled', 'Отменен'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('external_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID внешнего платежа')),
                ('provider_payment_charge_id', models.CharField(blank=True, max_length=200, verbose_name='ID провайдера')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
