# Generated by Django 5.2.6 on 2025-09-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_price_orderitem_addons_price_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_payload',
            field=models.CharField(blank=True, max_length=255, verbose_name='Payload инвойса'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shipping_option_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID способа доставки'),
        ),
        migrations.AddField(
            model_name='payment',
            name='telegram_payment_charge_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID платежа Telegram'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('telegram', 'Telegram Payments'), ('card', 'Банковская карта'), ('cash', 'Наличные'), ('online', 'Онлайн-платеж')], default='telegram', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ'),
        ),
    ]
