# Generated by Django 5.2.6 on 2025-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='allows_write_to_pm',
            field=models.BooleanField(default=False, verbose_name='Разрешает писать в ЛС'),
        ),
    ]
