# Generated by Django 5.2.6 on 2025-09-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50, verbose_name='Тип сообщения')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение бота',
                'verbose_name_plural': 'Сообщения бота',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(blank=True, max_length=100, verbose_name='Текущий шаг')),
                ('session_data', models.JSONField(default=dict, verbose_name='Данные сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafes.cafe', verbose_name='Текущее кафе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская сессия',
                'verbose_name_plural': 'Пользовательские сессии',
            },
        ),
    ]
