# Generated by Django 5.2.6 on 2025-10-05 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-trophy', max_length=50)),
                ('required_money', models.IntegerField(blank=True, null=True)),
                ('required_reputation', models.IntegerField(blank=True, null=True)),
                ('required_employees', models.IntegerField(blank=True, null=True)),
                ('required_customers', models.IntegerField(blank=True, null=True)),
                ('required_day', models.IntegerField(blank=True, null=True)),
                ('required_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='My Startup', max_length=100)),
                ('money', models.IntegerField(default=1000)),
                ('reputation', models.IntegerField(default=0)),
                ('employees', models.IntegerField(default=1)),
                ('customers', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('game_over', models.BooleanField(default=False)),
                ('victory', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('opportunity', 'Возможность'), ('challenge', 'Вызов'), ('news', 'Новость'), ('decision', 'Решение')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('day_occurred', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('money_change', models.IntegerField(default=0)),
                ('reputation_change', models.IntegerField(default=0)),
                ('employees_change', models.IntegerField(default=0)),
                ('customers_change', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='startup_game.gamesession')),
            ],
            options={
                'verbose_name': 'Game Event',
                'verbose_name_plural': 'Game Events',
                'ordering': ['-day_occurred'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_game.achievement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_game.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
