# Generated by Django 5.2.6 on 2025-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='industry',
            field=models.CharField(choices=[('IT', 'Информационные технологии'), ('FOOD', 'Еда и рестораны'), ('RETAIL', 'Розничная торговля'), ('HEALTH', 'Здравоохранение'), ('EDUCATION', 'Образование')], default='IT', max_length=50),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_time',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_event_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_decision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='dice_roll',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='money',
            field=models.IntegerField(default=500),
        ),
    ]