# Generated by Django 5.2.6 on 2025-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_game', '0002_add_game_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='prototype_skill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='presentation_skill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pitching_skill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='team_skill',
            field=models.IntegerField(default=0),
        ),
    ]