# Generated by Django 5.2.6 on 2025-10-06 12:30

from django.db import migrations


def reset_skills_for_existing_sessions(apps, schema_editor):
    """Обнуляем навыки для всех существующих игровых сессий"""
    GameSession = apps.get_model('startup_game', 'GameSession')
    GameSession.objects.all().update(
        prototype_skill=0,
        presentation_skill=0,
        pitching_skill=0,
        team_skill=0
    )


def reverse_reset_skills(apps, schema_editor):
    """Обратная миграция - ничего не делаем"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('startup_game', '0003_add_skills'),
    ]

    operations = [
        migrations.RunPython(reset_skills_for_existing_sessions, reverse_reset_skills),
    ]