# Generated by Django 5.2.6 on 2025-09-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe', verbose_name='Кафе')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['cafe', 'order', 'name'],
                'unique_together': {('cafe', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='menu_items/', verbose_name='Изображение')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Вес/объем')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe', verbose_name='Кафе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Позиции меню',
                'ordering': ['cafe', 'category', 'order', 'name'],
            },
        ),
    ]
