# Generated by Django 5.2.6 on 2025-09-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная группа')),
                ('max_selections', models.PositiveIntegerField(default=1, verbose_name='Максимум выборов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe', verbose_name='Кафе')),
            ],
            options={
                'verbose_name': 'Группа добавок',
                'verbose_name_plural': 'Группы добавок',
                'ordering': ['cafe', 'order', 'name'],
                'unique_together': {('cafe', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название добавки')),
                ('addon_type', models.CharField(choices=[('milk', 'Молоко'), ('syrup', 'Сироп'), ('spice', 'Специи'), ('extra', 'Дополнительно'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип добавки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe', verbose_name='Кафе')),
                ('categories', models.ManyToManyField(blank=True, to='menu.category', verbose_name='Применимо к категориям')),
                ('menu_items', models.ManyToManyField(blank=True, to='menu.menuitem', verbose_name='Применимо к позициям')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.addongroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Добавка',
                'verbose_name_plural': 'Добавки',
                'ordering': ['cafe', 'group', 'addon_type', 'order', 'name'],
                'unique_together': {('cafe', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название варианта')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Изменение цены')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem', verbose_name='Позиция меню')),
            ],
            options={
                'verbose_name': 'Вариант размера',
                'verbose_name_plural': 'Варианты размеров',
                'ordering': ['menu_item', 'order', 'name'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
    ]
