# Generated by Django 5.2.6 on 2025-09-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_addongroup_addon_menuitemvariant'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addons_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена добавок'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая цена'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена за единицу'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitemvariant', verbose_name='Вариант размера'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена варианта'),
        ),
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.addon', verbose_name='Добавка')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='orders.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Добавка к позиции',
                'verbose_name_plural': 'Добавки к позициям',
                'unique_together': {('order_item', 'addon')},
            },
        ),
    ]
