# Generated by Django 5.2.6 on 2025-09-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_staff_notification_fields'),
        ('orders', '0002_remove_orderitem_price_orderitem_addons_price_and_more'),
    ]

    operations = [
    ]
